const tldata={
	"bt1":"Inicio",
	"bt2":"Acerca de",
	"bt3":"Los bots",
	"button_lang":"English",
	"subt":"Bots de Telegram",
	"p1t":"¿Qué es Bots Of Charles?",
	"p1c":"Bots Of Charles (BoC) es un proyecto de bots de Telegram<br>Los bots están orientados a la administración y transferencia de archivos",
	"p2t":"Acerca de",
	"p2c1":"¿Qué es este sitio?",
	"p2c2":"Este es el sitio web del proyecto<br>En este sitio puede aprender a usar los bots",
	"p3t":"Acerca de",
	"p3t1":"Canal de Telegram",
	"p3t1c":"En el canal de Telegram de BoC se publican noticias y avisos de mantenimiento sobre los bots<br>Es la fuente principal de información para el proyecto",
	"p3t1b":"Ir al canal de Telegram",
	"p3t2":"Grupo de Telegram",
	"p3t2c":"El grupo te Telegram correspondiente al canal de BoC es un grupo de soporte técnico<br>Antes de preguntar sobre el uso del bot en el grupo, asegúrese de haber leido la documentación<br>En el grupo solo se habla inglés y español",
	"p3t2b":"Ir al grupo de Telegram",
	"p4t":"Los bots",
	"p4t1b1":"Guía de usuario",
	"p4t1b2":"Referencia de comandos",
	"p4t2b1":"Guía de usuario",
	"p4t2b2":"Referencia de comandos"
}
