const tldata={
	"bt1":"Inicio",
	"bt2":"Menú",
	"bt3":"Arriba",
	"bt4":"English",
	"page_title":"Guía de MF Shell",
	"subt":"Bots de Telegram",
	"p1t":"Menú",
	"p1b1":"Introducción",
	"p1b2":"El Sistema de Archivos",
	"p1b3":"Los selectores",
	"p1b4":"Límites y colas",
	"p1b5":"Conocimiento extra",
	"p2t":"Introducción",
	"p2c1":"<br><strong>Este bot no es normal</strong><br><br>En Telegram, la mayoría de bots para descargar y bots de leech tienen este 'efecto boomerang': les das algo, ya sea un archivo de Telegram, o una URL que conduce a un archivo, ellos hacen 'lo suyo' y al terminar suben al chat, todo esto se considera 'normal'. Lo primero que debe saber es que MF Shell no es un bot 'normal', ese 'efecto boomerang' no existe en el bot porque hay dos formas principales para sacar los archivos. La primera es la típica subida del bot al chat y la segunda es compartir los archivos vía web, también conocido como 'File-to-Link'",
	"p2c2":"<br><strong>Características de MF Shell</strong><br><br>→ Organice sus archivos como guste. Crear carpeta, renombrar archivos (en masa también), borrar archivos, extraer archivos ZIP, RAR, agrupar archivos en 7Z, y mucho más<br>→ Descarga contenido de donde sea. No se trata del típico Youtube o MEGA, aquí hay soporte directo desde archivos y carpetas de Google Drive, hasta aplicaciones de Android e incluso comics y manga<br>→ Creado para trabajos grandes. MF Shell tiene sistemas de listas de espera y colas. Los procesos encolados pueden pausarse o cancelarse, puedes modificar elementos en una cola. Las listas de espera son para racionar los recursos de cómputo del bot<br>→ FTL con esteroides. La interfaz web es muy útil para descargar grandes cantidades de contenido alojado en el bot",
	"p2c3":"<br><strong>Tutorial en vídeo</strong><br><br>La guía puede llegar a ser densa de leer, es por eso que tenemos un tutorial en vídeo mostrando lo básico que se puede hacer en el bot",
	"p2b":"Ver el vídeo",
	"p2c4":"El vídeo es solo una mera introducción para entender el uso general que se le da al bot, y el flujo de trabajo<br>El vídeo a penas rasca la superficie, especialmente con lo básico, asi que si ya vió el vídeo, siga leyendo la guía hasta el final y luego vaya a la referencia de comandos",
	"p2next":"Empezar a aprender",
	"p3t":"El Sistema de Archivos",
	"p3c1":"<br><strong>Teoría</strong><br><br>En el bot, cada usuario tiene su propio directorio (carpeta), donde puede trabajar y dentro de ese directorio, el usuario puede crear más subdirectorios y agrupar archivos",
	"p3c2":"Hay una ubicación (ruta) que es el directorio actual de trabajo (CWD en inglés). Un usuario puede cambiar de CWD yendo más profundo o más arriba en la estructura donde se encuentra. Cada CWD tiene un padre, a exceptión de la raiz '/'<br>Si todo esto le parece confuso, piense en un árbol de cabeza, donde cada nodo del árbol (directorio) tiene un nombre",
	"p3c3":"<br><strong>Mirar, moverse</strong><br><br>Para ver los contenidos del CWD, así como el CWD actual, puede ejecutar el comando '/ls' de esta forma:",
	"p3c4":"La siguiente imagen es un ejemplo de listado de directorio usando '/ls'",
	"p3c5":"Como se puede ver en esta imagen, al principio del mensaje se puede ver la ruta del CWD y por cada fila (cada elemento) se puede diferenciar entre archivo o directorio solamente mirando el ícono, pero lo más importante de todo esto es lo que hay antes del icono: ese número es el índice del elemento. En MF Shell cuando se seleccionan archivos o directorios, no se hace mediante el nombre del archivo, se hace usando el índice que ocupa en el CWD<br>Sabiendo lo anterior, podemos ver alguna ubicación en específico, como por ejmplo, ese directorio llamado 'stufffff' que ocupa índice 1:",
	"p3c6":"<br><strong>No me he movido</strong><br><br>El comando '/ls' solamente es útil para observar otros elementos, pero observar otra ruta no te hace cambiar el CWD a esa ruta. Hay 2 comandos para cambiar de CWD: '/cd' y '/back'<br>El comando '/cd' puede cambiar el CWD a un subdirectorio:",
	"p3c7":"Y el comando '/back' cambia el CWD al directorio padre del WD actual:",
	"p3c8":"Usar como argumento el índice de un elemento en un comando se llama 'Selección simple', ya que en ambos casos ('/ls' y '/cd') se seleccionó solamente uno<br>El próximo capítulo trata sobre los tipos de selección en MF Shell",
	"p4t":"Tipos de selección",
	"p4c1":"<br><strong>Intro</strong><br><br>En el capítulo anterior se vió lo básico acerca del sistema de archivos en MF Shell. En este capítulo vamos a ver lo que son los tipos de selección (también llamados selectores) y cómo podemos usarlos para seleccionar elementos",
	"p4c2":"Hay 3 tipos de selectores:<br>→ Selector simple<br>→ Selector de rango<br>→ Selector libre",
	"p4c3":"<br><strong>Selector simple</strong><br><br>Forma: N. Donde N es un entero<br>En el contexto de la administración de archvos, cuando N es positivo o cero, se está apuntando a un elemento que debe existir en el CWD, vimos un ejemplo de esto en el capítulo anterior, pero veamos otro ejemplo con el comando '/mv'<br>El comando '/mv' se usa para mover archivos y directorios y también se usa para renombrar, todo depende de la ejecución. Probemos primero renombrar a un archivo:",
	"p4c4":"El archivo ha sido renombrado, ahora vamos a moverlo de sitio, pero primero hay que ejecutar '/ls' ya que debido a que el nombre del archivo cambió, es probable que su índice en el CWD haya cambiado",
	"p4c5":"Como podemos ver en la imagen, el archivo cambió de posición al índice X. Ejecutamos ahora '/mv':",
	"p4c6":"Si corremos '/ls' para ver al directorio que ocupa el índice no. 2, veremos el archivo que recién movimos",
	"p4c7":"¿Qué pasa si N (el índice) es negativo (menor que cero)? En este caso, N (el índice a seleccionar) selecciona a un pariente de CWD y (obviamente) lo selecciona como directorio<br>Por ejemplo, supongamos que nuestro CWD es '/some/files/around/here/' y ejecutamos:",
	"p4c8":"Lo que pasó aquí es que cambiamos nuestro CWD de '/some/files/around/here/' a '/some/files/', y si nos fijamos bien, lo que hicimos fue movernos 2 niveles por encima",
	"p4c9":"",
}
